# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aetherops_pb2 as aetherops__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aetherops_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TopologyServiceStub:
    """─────────────────────────────────────────────
    Go → Python: topology & anomaly streaming
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTopology = channel.unary_unary(
                '/aetherops.TopologyService/GetTopology',
                request_serializer=aetherops__pb2.GetTopologyRequest.SerializeToString,
                response_deserializer=aetherops__pb2.TopologySnapshot.FromString,
                _registered_method=True)
        self.SubscribeAnomalyEvents = channel.unary_stream(
                '/aetherops.TopologyService/SubscribeAnomalyEvents',
                request_serializer=aetherops__pb2.AnomalySubscription.SerializeToString,
                response_deserializer=aetherops__pb2.AnomalyEvent.FromString,
                _registered_method=True)


class TopologyServiceServicer:
    """─────────────────────────────────────────────
    Go → Python: topology & anomaly streaming
    ─────────────────────────────────────────────

    """

    def GetTopology(self, request, context):
        """GetTopology returns the current service graph snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeAnomalyEvents(self, request, context):
        """SubscribeAnomalyEvents streams anomaly events as they are detected.
        The Go side evaluates anomalies every AnalysisInterval (default 15s)
        and pushes events to all subscribed Python consumers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopologyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopology,
                    request_deserializer=aetherops__pb2.GetTopologyRequest.FromString,
                    response_serializer=aetherops__pb2.TopologySnapshot.SerializeToString,
            ),
            'SubscribeAnomalyEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeAnomalyEvents,
                    request_deserializer=aetherops__pb2.AnomalySubscription.FromString,
                    response_serializer=aetherops__pb2.AnomalyEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aetherops.TopologyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aetherops.TopologyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TopologyService:
    """─────────────────────────────────────────────
    Go → Python: topology & anomaly streaming
    ─────────────────────────────────────────────

    """

    @staticmethod
    def GetTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherops.TopologyService/GetTopology',
            aetherops__pb2.GetTopologyRequest.SerializeToString,
            aetherops__pb2.TopologySnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeAnomalyEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aetherops.TopologyService/SubscribeAnomalyEvents',
            aetherops__pb2.AnomalySubscription.SerializeToString,
            aetherops__pb2.AnomalyEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RemediationServiceStub:
    """─────────────────────────────────────────────
    Python → Go: risk assessment & remediation
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateRemediation = channel.unary_unary(
                '/aetherops.RemediationService/EvaluateRemediation',
                request_serializer=aetherops__pb2.RemediationRequest.SerializeToString,
                response_deserializer=aetherops__pb2.RemediationReport.FromString,
                _registered_method=True)
        self.ExecuteRemediation = channel.unary_unary(
                '/aetherops.RemediationService/ExecuteRemediation',
                request_serializer=aetherops__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=aetherops__pb2.ExecuteResponse.FromString,
                _registered_method=True)


class RemediationServiceServicer:
    """─────────────────────────────────────────────
    Python → Go: risk assessment & remediation
    ─────────────────────────────────────────────

    """

    def EvaluateRemediation(self, request, context):
        """EvaluateRemediation simulates the blast radius of a proposed action.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteRemediation(self, request, context):
        """ExecuteRemediation executes a graded remediation action.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemediationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateRemediation': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateRemediation,
                    request_deserializer=aetherops__pb2.RemediationRequest.FromString,
                    response_serializer=aetherops__pb2.RemediationReport.SerializeToString,
            ),
            'ExecuteRemediation': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteRemediation,
                    request_deserializer=aetherops__pb2.ExecuteRequest.FromString,
                    response_serializer=aetherops__pb2.ExecuteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aetherops.RemediationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aetherops.RemediationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemediationService:
    """─────────────────────────────────────────────
    Python → Go: risk assessment & remediation
    ─────────────────────────────────────────────

    """

    @staticmethod
    def EvaluateRemediation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherops.RemediationService/EvaluateRemediation',
            aetherops__pb2.RemediationRequest.SerializeToString,
            aetherops__pb2.RemediationReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteRemediation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherops.RemediationService/ExecuteRemediation',
            aetherops__pb2.ExecuteRequest.SerializeToString,
            aetherops__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GraphDatabaseServiceStub:
    """─────────────────────────────────────────────
    Go internal: topology sync to Neo4j
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncTopology = channel.unary_unary(
                '/aetherops.GraphDatabaseService/SyncTopology',
                request_serializer=aetherops__pb2.TopologySnapshot.SerializeToString,
                response_deserializer=aetherops__pb2.SyncAck.FromString,
                _registered_method=True)


class GraphDatabaseServiceServicer:
    """─────────────────────────────────────────────
    Go internal: topology sync to Neo4j
    ─────────────────────────────────────────────

    """

    def SyncTopology(self, request, context):
        """SyncTopology pushes the current topology snapshot to a graph database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphDatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncTopology,
                    request_deserializer=aetherops__pb2.TopologySnapshot.FromString,
                    response_serializer=aetherops__pb2.SyncAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aetherops.GraphDatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aetherops.GraphDatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphDatabaseService:
    """─────────────────────────────────────────────
    Go internal: topology sync to Neo4j
    ─────────────────────────────────────────────

    """

    @staticmethod
    def SyncTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherops.GraphDatabaseService/SyncTopology',
            aetherops__pb2.TopologySnapshot.SerializeToString,
            aetherops__pb2.SyncAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
