"""
AetherOps — Multi-Agent Cognitive Workflow.

Architecture: Planner → Supervisor → Expert Agents (+ Critic)
  - Planner          LLM-generated dynamic execution plan based on anomaly
  - Supervisor       route to next agent per plan, handle critic feedback loops
  - Topology Analyst  fetch service graph from Go data plane
  - Causal Analyst    fetch metrics + run causal discovery
  - LLM Diagnostician LLM-based root cause diagnosis (multi-turn)
  - Critic           reflection agent — reviews diagnosis quality before proceeding
  - Risk Assessor     blast radius evaluation
  - Remediation Executor  graded remediation + incident memory storage
"""

from __future__ import annotations

import json
import logging
import os
import time
from dataclasses import asdict
from typing import Any, Literal, Optional, TypedDict

from aetherops.core.causal_inference import run_causal_discovery
from aetherops.core.llm_diagnosis import diagnose
from aetherops.core.llm_provider import ProviderFactory
from aetherops.core.multi_turn_diagnosis import diagnose_multi_turn, DataRequest
from aetherops.core.metrics_fetcher import fetch_recent_metrics
from aetherops.core.risk_client import assess_remediation, execute_remediation
from aetherops.core.alert_correlation import AlertCorrelator, AlertEvent
from aetherops.core.feedback import (
    get_feedback_store, get_rollback_assistant,
    ApprovalStatus, AuditEntry, RiskLevel,
)
from aetherops.core.agent_observability import (
    trace_agent, record_workflow_metrics, Span,
)
from aetherops.core.hooks import (
    HookEvent, trigger_hook,
)
from aetherops.core.incident_memory import IncidentMemory

logger = logging.getLogger(__name__)


def _fetch_topology(include_healthy: bool = False):
    """Shared helper: fetch topology via MCP, returns a snapshot."""
    from aetherops.core.mcp_client import MCPClient, run_async

    mcp_addr = os.getenv("AETHEROPS_MCP_ADDR", "http://localhost:50052")
    client = MCPClient(address=mcp_addr)
    run_async(client.connect())
    snapshot = run_async(client.get_topology(include_healthy=include_healthy))
    client.close()
    return snapshot


AGENTS = Literal[
    "planner",
    "topology_analyst",
    "causal_analyst",
    "llm_diagnostician",
    "critic",
    "risk_assessor",
    "remediation_executor",
    "finish",
]

# Max critic re-diagnosis loops before forcing through
MAX_CRITIC_LOOPS = 2


# ── State Definition ──

class DiagnosisState(TypedDict):
    """Shared state passed between LangGraph nodes."""

    # Trigger
    anomaly_event: Optional[dict]
    anomaly_detected_at: float       # time.time() when anomaly first received, for MTTR
    topology_snapshot: Optional[dict]

    # Step 1: Data fetching
    metrics_data: Optional[Any]  # pandas DataFrame

    # Step 2: Causal inference
    causal_graph: Optional[dict]
    causal_method: str

    # Step 3: LLM diagnosis
    diagnosis_report: Optional[dict]
    diagnosis_confidence: float
    diagnosis_loop_count: int

    # Critic / Reflection
    critic_feedback: Optional[str]   # feedback from critic to diagnostician
    critic_approves: Optional[bool]  # None=not yet reviewed, True/False
    critic_loop_count: int

    # Step 4: Risk assessment
    risk_report: Optional[dict]

    # Step 5: Remediation
    execution_result: Optional[dict]

    # Step 6: Recovery verification
    topology_before: Optional[dict]
    recovery_report: Optional[str]

    # RAG context (injected by main daemon)
    rag_context: Optional[str]

    # Plan (dynamic, generated by Planner)
    plan: Optional[List[str]]
    plan_step_index: int
    plan_rationale: Optional[str]    # why this plan was chosen

    # Supervisor meta-state
    next_agent: str
    supervisor_instruction: Optional[str]

    # Observability
    trace_spans: List[dict]

    # Completion
    completed: bool
    workflow_error: Optional[str]


# ── Planner ──

PLANNER_SYSTEM_PROMPT = """You are an expert SRE operations planner. Given an anomaly event and historical context, create a step-by-step diagnosis and remediation plan.

## Available Agents
- `topology_analyst` — Fetches live service topology from eBPF data plane
- `causal_analyst` — Fetches Prometheus metrics and runs causal discovery (LPCMCI)
- `llm_diagnostician` — LLM-based root cause analysis with multi-turn refinement
- `critic` — Reviews the diagnosis report for quality, consistency, and completeness
- `risk_assessor` — Evaluates blast radius and risk level of recommended actions
- `remediation_executor` — Executes remediation, verifies recovery, stores to RAG

## Planning Rules
1. topology_analyst and causal_analyst are always needed first (they provide data)
2. llm_diagnostician must come after data is available
3. critic should follow llm_diagnostician to validate diagnosis quality
4. risk_assessor and remediation_executor come last
5. If the anomaly matches a known pattern (DB, network, cache, resource, hotspot), you may suggest re-ordering or repeating certain steps

## Output Format
```json
{
  "steps": ["topology_analyst", "causal_analyst", "llm_diagnostician", "critic", "risk_assessor", "remediation_executor"],
  "reasoning": "Brief explanation of why this plan was chosen"
}
```
"""


def _call_llm_for_plan(anomaly_event: dict, rag_context: str = "") -> dict:
    """Call LLM to generate a diagnosis plan."""
    provider = ProviderFactory.from_env()
    if provider is None:
        logger.info("No LLM provider for planner — using default plan")
        return {
            "steps": [
                "topology_analyst", "causal_analyst",
                "llm_diagnostician", "critic",
                "risk_assessor", "remediation_executor",
            ],
            "reasoning": "Default plan (LLM not available)",
        }

    user_msg = (
        f"## Anomaly Event\n"
        f"```json\n{json.dumps(anomaly_event, indent=2)}\n```\n"
    )
    if rag_context:
        user_msg += f"\n## Historical Context (similar past incidents)\n{rag_context[:2000]}\n"

    try:
        raw = provider.chat(PLANNER_SYSTEM_PROMPT, user_msg, max_tokens=1024, temperature=0.2, timeout=30)
        if raw is None:
            raise RuntimeError("provider.chat returned None")
        plan_data = _robust_json_extract(raw)
        steps = plan_data.get("steps", [])
        if not steps:
            raise ValueError("empty plan")
        return plan_data

    except Exception as e:
        logger.warning("Planner LLM call failed (%s) — using default plan", e)
        return {
            "steps": [
                "topology_analyst", "causal_analyst",
                "llm_diagnostician", "critic",
                "risk_assessor", "remediation_executor",
            ],
            "reasoning": f"Default plan (LLM error: {e})",
        }


@trace_agent("planner")
def planner(state: DiagnosisState) -> Dict:
    """Generate a dynamic execution plan based on anomaly + RAG context."""
    anomaly = state.get("anomaly_event", {})
    rag = state.get("rag_context", "")
    plan_data = _call_llm_for_plan(anomaly, rag)

    steps = plan_data.get("steps", [])
    logger.info("Planner: %d steps — %s", len(steps), plan_data.get("reasoning", ""))

    trigger_hook(HookEvent.PLAN_GENERATED, steps=steps, reasoning=plan_data.get("reasoning", ""))

    return {
        "plan": steps,
        "plan_step_index": 0,
        "plan_rationale": plan_data.get("reasoning", ""),
    }


# ── Expert Agents ──

@trace_agent("topology_analyst")
def topology_analyst(state: DiagnosisState) -> Dict:
    """Expert 1: Fetch current service topology from Go MCP server."""
    try:
        snapshot = _fetch_topology(include_healthy=False)
        logger.info("TopologyAnalyst: fetched %d nodes, %d edges",
                     snapshot.node_count, snapshot.edge_count)
        return {
            "topology_snapshot": {
                "nodes": [n for n in snapshot.nodes if n["avg_latency_ms"] > 0],
                "edges": [e for e in snapshot.edges if e["anomaly_score"] > 0],
                "node_count": snapshot.node_count,
                "edge_count": snapshot.edge_count,
            }
        }
    except Exception as e:
        logger.error("TopologyAnalyst failed: %s", e)
        return {"topology_snapshot": {"nodes": [], "edges": [], "error": str(e)}}


@trace_agent("causal_analyst")
def causal_analyst(state: DiagnosisState) -> Dict:
    """Expert 2: Fetch Prometheus metrics and run causal inference."""
    prom_url = os.getenv("PROMETHEUS_URL", "http://localhost:9090")
    df = fetch_recent_metrics(
        prometheus_url=prom_url,
        window_minutes=5,
        step_seconds=15,
    )

    metrics_df = df
    topo = state.get("topology_snapshot", {})

    # --- Sparsify: filter metrics columns to only anomalous/relevant services ---
    # PC algorithm is O(n²) in the number of variables. With 1000+ nodes,
    # this is prohibitively expensive. Identify the subset of relevant variables.
    if metrics_df is not None and not metrics_df.empty:
        suspect_ids: set[str] = set()

        # 1. Primary suspect from anomaly event
        event_node = state.get("anomaly_event", {}).get("node_id", "")
        if event_node:
            suspect_ids.add(event_node)
        # 2. Suspect chain from the propagation path
        for node in state.get("anomaly_event", {}).get("suspect_chain", []):
            suspect_ids.add(node)
        # 3. Nodes with anomaly_score > 0 (already filtered by topology_analyst)
        for edge in topo.get("edges", []):
            if edge.get("src"):
                suspect_ids.add(edge["src"])
            if edge.get("dst"):
                suspect_ids.add(edge["dst"])
        # 4. Nodes with elevated latency from topology snapshot
        for node in topo.get("nodes", []):
            if node.get("id") and node.get("avg_latency_ms", 0) > 0:
                suspect_ids.add(node["id"])

        # Extract IP:port fragments for column matching
        suspect_fragments = set()
        for sid in suspect_ids:
            suspect_fragments.add(sid)
            # Extract IP:port from "service->ip:port" format
            if "->" in sid:
                parts = sid.split("->")
                suspect_fragments.add(parts[0])
                suspect_fragments.add(parts[1])
            # Just the IP part (without port)
            if ":" in sid:
                ip_part = sid.split(":")[0]
                # Only add if looks like an IP
                if ip_part and ip_part[0].isdigit():
                    suspect_fragments.add(ip_part)

        # Filter DataFrame columns to only those referencing suspect services
        n_before = len(metrics_df.columns)
        relevant_cols = [
            c for c in metrics_df.columns
            if any(frag.lower() in c.lower() for frag in suspect_fragments if frag)
        ]
        if relevant_cols:
            metrics_df = metrics_df[relevant_cols]
        n_after = len(metrics_df.columns)
        logger.info(
            "CausalAnalyst: sparsified metrics %d→%d columns (from %d suspect fragments)",
            n_before, n_after, len(suspect_fragments),
        )

    if metrics_df is not None and hasattr(metrics_df, "to_dict"):
        metrics_dict = metrics_df.to_dict()
    else:
        metrics_dict = {}

    context = {
        "known_topology": topo,
        "metrics_summary": metrics_dict,
    }

    try:
        result = run_causal_discovery(
            metrics_df=metrics_df,
            method=state.get("causal_method", "LPCMCI"),
            alpha=0.05,
            context=context,
        )
        logger.info("CausalAnalyst: inferred %d causal edges", len(result.edges))
        return {
            "metrics_data": df,
            "causal_graph": {
                "nodes": result.nodes,
                "edges": [(s, d, t) for s, d, t in result.edges],
            },
        }
    except Exception as e:
        logger.error("CausalAnalyst failed: %s", e)
        return {
            "metrics_data": df,
            "causal_graph": {"nodes": [], "edges": [], "error": str(e)},
        }


@trace_agent("llm_diagnostician")
def llm_diagnostician(state: DiagnosisState) -> Dict:
    """Expert 3: Run multi-turn LLM diagnosis on causal graph + anomaly context."""
    causal_graph = state.get("causal_graph", {})
    anomaly_context = {
        "topology": state.get("topology_snapshot", {}),
        "anomaly_event": state.get("anomaly_event", {}),
    }

    # If critic provided feedback, inject it as additional context
    critic_feedback = state.get("critic_feedback")
    if critic_feedback:
        anomaly_context["critic_feedback"] = critic_feedback
        logger.info("LLMDiagnostician: incorporating critic feedback")

    result = diagnose_multi_turn(
        causal_graph=causal_graph,
        anomaly_context=anomaly_context,
        max_turns=int(os.getenv("MAX_DIAGNOSIS_TURNS", "2")),
    )

    report = result.final_report
    logger.info("LLMDiagnostician: root_cause=%s confidence=%.2f turns=%d improved=%s",
                 report.root_cause, report.confidence, result.turn_count, result.improved)

    trigger_hook(HookEvent.DIAGNOSIS_COMPLETE,
        root_cause=report.root_cause, confidence=report.confidence,
        affected_services=report.affected_services,
        turn_count=result.turn_count, improved=result.improved)

    return {
        "diagnosis_report": {
            "root_cause": report.root_cause,
            "confidence": report.confidence,
            "explanation": report.explanation,
            "affected_services": report.affected_services,
            "recommended_actions": report.recommended_actions,
            "multi_turn_data": {
                "turn_count": result.turn_count,
                "improved": result.improved,
                "data_requests": [asdict(r) for r in result.data_requests],
            },
        },
        "diagnosis_confidence": report.confidence,
        "diagnosis_loop_count": state.get("diagnosis_loop_count", 0) + 1,
        # Reset critic state for the new diagnosis
        "critic_feedback": None,
        "critic_approves": None,
    }


# ── Critic / Reflection Agent ──

CRITIC_SYSTEM_PROMPT = """You are a senior SRE reviewer. Your job is to review a diagnosis report before remediation is executed.

## Review Checklist
1. **Logical consistency**: Does the root cause explanation match the evidence?
2. **Confidence calibration**: Is the confidence score appropriate given the evidence?
3. **Action appropriateness**: Do the recommended actions match the root cause?
4. **Evidence gaps**: Are there missing pieces of data that weaken the diagnosis?

## Output Format
```json
{
  "approves": true,
  "feedback": "Brief justification of approval or what needs to be re-analyzed",
  "confidence_adjustment": 0.0
}
```

- `approves`: true if the diagnosis is sound, false if it needs revision
- `feedback`: if approving, summarize what looks good; if rejecting, explain what's missing or wrong
- `confidence_adjustment`: optional delta to apply to the confidence score (e.g., -0.1 to reduce overconfidence)
"""


def _robust_json_extract(text: str) -> dict:
    """Try multiple strategies to extract valid JSON from LLM response text."""
    # Strategy 1: extract from ```json code block
    if "```json" in text:
        candidate = text.split("```json")[1].split("```")[0].strip()
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass

    # Strategy 2: extract from any ``` code block
    if "```" in text:
        candidate = text.split("```")[1].split("```")[0].strip()
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass

    # Strategy 3: outermost { ... } pair
    brace_start = text.find("{")
    brace_end = text.rfind("}")
    if brace_start >= 0 and brace_end > brace_start:
        candidate = text[brace_start:brace_end + 1]
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass

    # Strategy 4: regex for any JSON-like object and look for known keys
    import re
    for m in re.finditer(r'\{[^{}]*\}', text, re.DOTALL):
        try:
            result = json.loads(m.group())
            if "approves" in result or "feedback" in result:
                return result
        except json.JSONDecodeError:
            continue

    raise ValueError("No valid JSON extracted from LLM response")


def _call_llm_as_critic(diagnosis_report: dict) -> dict:
    """Call LLM to review a diagnosis report."""
    provider = ProviderFactory.from_env()
    if provider is None:
        # No LLM — always approve with heuristic check
        confidence = diagnosis_report.get("confidence", 0)
        if confidence < 0.3:
            return {"approves": False, "feedback": "Very low confidence — consider re-analysis", "confidence_adjustment": 0}
        return {"approves": True, "feedback": "Auto-approved (critic LLM unavailable)", "confidence_adjustment": 0}

    user_msg = f"## Diagnosis Report\n```json\n{json.dumps(diagnosis_report, indent=2, default=str)}\n```\n"

    try:
        raw = provider.chat(CRITIC_SYSTEM_PROMPT, user_msg, max_tokens=1024, temperature=0.2, timeout=30)
        if raw is None:
            raise RuntimeError("provider.chat returned None")
        return _robust_json_extract(raw)

    except Exception as e:
        logger.warning("Critic LLM call failed (%s) — defaulting to approve", e)
        return {"approves": True, "feedback": f"Auto-approved (critic error: {e})", "confidence_adjustment": 0}


@trace_agent("critic")
def critic(state: DiagnosisState) -> Dict:
    """Review the diagnosis report and decide if re-analysis is needed."""
    report = state.get("diagnosis_report", {})
    if not report or not report.get("root_cause"):
        return {"critic_approves": False, "critic_feedback": "No diagnosis report to review"}

    review = _call_llm_as_critic(report)

    approves = review.get("approves", True)
    feedback = review.get("feedback", "")
    conf_adj = review.get("confidence_adjustment", 0)
    loop_count = state.get("critic_loop_count", 0) + 1

    # Adjust confidence
    current_conf = state.get("diagnosis_confidence", 0)
    adjusted_conf = max(0.0, min(1.0, current_conf + conf_adj))

    logger.info(
        "Critic: approves=%s loop=%d/%d conf=%.2f→%.2f feedback=%s",
        approves, loop_count, MAX_CRITIC_LOOPS,
        current_conf, adjusted_conf, feedback[:80],
    )

    trigger_hook(HookEvent.CRITIC_REVIEWED,
        approves=approves, loop_count=loop_count,
        feedback=feedback, confidence_adjustment=conf_adj)

    result = {
        "critic_approves": approves,
        "critic_feedback": feedback,
        "critic_loop_count": loop_count,
        "diagnosis_confidence": adjusted_conf,
    }

    # If rejected but we have loops left, the supervisor will re-route to diagnostician
    if not approves and loop_count < MAX_CRITIC_LOOPS:
        result["next_agent"] = "llm_diagnostician"

    return result


# ── Risk Assessor & Remediation Executor (unchanged logic) ──

@trace_agent("risk_assessor")
def risk_assessor(state: DiagnosisState) -> Dict:
    """Expert 4: Assess blast radius for the top recommended action."""
    report = state.get("diagnosis_report", {})
    actions = report.get("recommended_actions", [])

    if not actions:
        logger.warning("RiskAssessor: no actions to assess")
        return {"risk_report": {"error": "no actions to assess"}}

    top_action = actions[0]
    risk = assess_remediation(
        target_node=top_action.get("target", state.get("anomaly_event", {}).get("node_id", "")),
        action=top_action.get("action", "TC_DROP"),
        diagnosis=report,
    )
    logger.info("RiskAssessor: risk=%s budget=%.1f%%",
                 risk.get("risk_level"), risk.get("estimated_error_budget_consumption", 0))
    return {"risk_report": risk}


@trace_agent("remediation_executor")
def remediation_executor(state: DiagnosisState) -> Dict:
    """Expert 5: Execute remediation, verify recovery, generate fault report."""
    risk = state.get("risk_report", {})
    report = state.get("diagnosis_report", {})
    result: Dict[str, Any] = {}

    feedback = get_feedback_store()
    rollback = get_rollback_assistant()
    trace_id = f"exec-{int(time.time())}"
    anomaly_node = state.get("anomaly_event", {}).get("node_id", "unknown")

    trigger_hook(HookEvent.REMEDIATION_START,
        trace_id=trace_id, anomaly_node=anomaly_node,
        risk_level=risk.get("risk_level"), actions=report.get("recommended_actions"))
    anomaly_score_before = state.get("anomaly_event", {}).get("anomaly_score", 0)
    anomaly_detected_at = state.get("anomaly_detected_at", 0.0)

    # 5a. Execute graded remediation
    if risk.get("error"):
        result["execution_result"] = {"status": "skipped", "details": risk.get("error"), "trace_id": trace_id}
        feedback.audit(AuditEntry(
            timestamp_ns=time.time_ns(), agent="remediation_executor",
            action="skip", input_summary=risk.get("error", ""),
            output_summary="skipped", duration_ms=0,
            decision="skipped", trace_id=trace_id,
        ))
    else:
        actions = report.get("recommended_actions", [])
        if not actions:
            result["execution_result"] = {"status": "skipped", "details": "no actions", "trace_id": trace_id}
        else:
            top_action = actions[0]
            risk_level_str = risk.get("risk_level", "RISK_LOW")
            try:
                risk_enum = RiskLevel.HIGH if "HIGH" in risk_level_str else (
                    RiskLevel.MEDIUM if "MEDIUM" in risk_level_str else RiskLevel.LOW
                )
            except Exception:
                risk_enum = RiskLevel.LOW
            force = risk_enum == RiskLevel.LOW

            if risk_enum == RiskLevel.HIGH:
                feedback.record_approval(
                    trace_id=trace_id, node_id=anomaly_node,
                    diagnosis_report=report, action=top_action,
                    status=ApprovalStatus.PENDING,
                    comment="HIGH risk action pending human approval",
                )
                result["execution_result"] = {
                    "status": "pending_approval",
                    "details": "HIGH risk requires human approval",
                    "trace_id": trace_id,
                }
            else:
                exec_result = execute_remediation(
                    target_node=top_action.get("target", ""),
                    action=top_action.get("action", "TC_DROP"),
                    force=force,
                )
                exec_result["trace_id"] = trace_id
                result["execution_result"] = exec_result

                status = ApprovalStatus.AUTO_EXECUTED_LOW_RISK if force else ApprovalStatus.APPROVED
                feedback.record_approval(
                    trace_id=trace_id, node_id=anomaly_node,
                    diagnosis_report=report, action=top_action,
                    status=status,
                )
                feedback.audit(AuditEntry(
                    timestamp_ns=time.time_ns(), agent="remediation_executor",
                    action=top_action.get("action", ""),
                    input_summary=f"{anomaly_node} via {top_action.get('action', '')}",
                    output_summary=json.dumps({k: v for k, v in exec_result.items() if k != "trace_id"}),
                    duration_ms=0, decision=exec_result.get("status", "unknown"),
                    risk_level=risk_enum, trace_id=trace_id,
                ))
                logger.info("RemediationExecutor: status=%s id=%s trace=%s",
                             exec_result.get("status"), exec_result.get("execution_id"), trace_id)

    # 5b. Recovery verification
    recovery_report = _verify_recovery(
        anomaly_node=anomaly_node,
        anomaly_score_before=anomaly_score_before,
        execution_result=result.get("execution_result", {}),
        diagnosis_report=report,
        anomaly_detected_at=anomaly_detected_at,
    )
    result["recovery_report"] = recovery_report
    logger.info("RemediationExecutor: recovery verification complete")

    # Check if rollback is needed
    if rollback.needs_rollback(recovery_report):
        exec_result = result.get("execution_result", {})
        rb_result = rollback.execute_rollback(
            trace_id=trace_id,
            node_id=anomaly_node,
            original_action=report.get("recommended_actions", [{}])[0] if report.get("recommended_actions") else {},
            execution_id=exec_result.get("execution_id", ""),
        )
        result["rollback_result"] = rb_result
        logger.warning("Rollback executed for trace=%s", trace_id)

    # Record outcome
    status = result.get("execution_result", {}).get("status", "unknown")
    outcome = "success" if "Resolved" in recovery_report else (
        "partial" if "Partially" in recovery_report else "failure"
    )
    mttr_value = 0.0
    if anomaly_detected_at > 0:
        mttr_value = time.time() - anomaly_detected_at
    feedback.record_outcome(trace_id=trace_id, outcome=outcome, mttr_seconds=mttr_value)

    # 5c. Save to incident memory
    try:
        incident = IncidentMemory()
        incident.save(trace_id, {
            "status": result.get("execution_result", {}).get("status", "unknown"),
            "anomaly_node": anomaly_node,
            "root_cause": report.get("root_cause", "unknown"),
            "confidence": report.get("confidence", 0),
            "risk_level": risk.get("risk_level", "UNKNOWN"),
            "recovery": recovery_report[:200] if recovery_report else "",
        })
        logger.info("RemediationExecutor: incident saved to memory (id=%s)", trace_id)
    except Exception as e:
        logger.warning("Incident memory save failed (non-critical): %s", e)

    recovery_report = result.get("recovery_report", "")
    exec_result = result.get("execution_result", {})
    trigger_hook(HookEvent.REMEDIATION_COMPLETE,
        trace_id=trace_id, status=exec_result.get("status"),
        details=exec_result.get("details"))
    trigger_hook(HookEvent.RECOVERY_VERIFIED,
        trace_id=trace_id, outcome=recovery_report[:50] if recovery_report else "unknown")

    result["completed"] = True
    return result


def _verify_recovery(
    anomaly_node: str,
    anomaly_score_before: float,
    execution_result: dict,
    diagnosis_report: dict,
    anomaly_detected_at: float = 0.0,
) -> str:
    """Re-fetch metrics after remediation and generate a Markdown recovery report."""
    report_sections: list[str] = []
    ts = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())

    mttr_seconds = 0.0
    mttr_str = "N/A"
    if anomaly_detected_at > 0:
        mttr_seconds = time.time() - anomaly_detected_at
        if mttr_seconds < 120:
            mttr_str = f"{mttr_seconds:.0f}s"
        else:
            mins = int(mttr_seconds // 60)
            secs = int(mttr_seconds % 60)
            mttr_str = f"{mins}m {secs}s"

    exec_status = execution_result.get("status", "unknown")
    report_sections.append(f"# AetherOps Recovery Verification Report")
    report_sections.append(f"")
    report_sections.append(f"**Generated:** {ts}")
    report_sections.append(f"**Target Node:** `{anomaly_node}`")
    report_sections.append(f"**Remediation Status:** `{exec_status}`")
    report_sections.append(f"**MTTR:** `{mttr_str}`")
    report_sections.append(f"")

    root_cause = diagnosis_report.get("root_cause", "unknown")
    confidence = diagnosis_report.get("confidence", 0)
    report_sections.append(f"## Remediation Summary")
    report_sections.append(f"")
    report_sections.append(f"- **Root Cause:** {root_cause}")
    report_sections.append(f"- **Diagnosis Confidence:** {confidence:.1%}")
    report_sections.append(f"- **Anomaly Score (pre):** {anomaly_score_before:.2f}")
    if execution_result.get("execution_id"):
        report_sections.append(f"- **Execution ID:** `{execution_result['execution_id']}`")
    if execution_result.get("details"):
        report_sections.append(f"- **Details:** {execution_result['details']}")
    report_sections.append(f"")

    # Recovery verification — exponential backoff polling
    # Instead of a fixed 10s sleep, poll at 2s → 3s → 5s and return early if recovered.
    poll_backoff = [2, 3, 5]
    post_anomaly = 0.0
    post_latency = 0.0
    recovered = False

    for attempt, delay in enumerate(poll_backoff, 1):
        logger.info(
            "Recovery verification: polling attempt %d/%d (waiting %ds)...",
            attempt, len(poll_backoff), delay,
        )
        time.sleep(delay)

        try:
            snapshot = _fetch_topology(include_healthy=False)

            for edge in snapshot.edges:
                if edge.get("src") == anomaly_node or edge.get("dst") == anomaly_node:
                    if edge.get("anomaly_score", 0) > post_anomaly:
                        post_anomaly = edge.get("anomaly_score", 0)
                        post_latency = edge.get("avg_latency_ms", 0)

            recovered = post_anomaly < (anomaly_score_before * 0.3)
            if recovered and post_latency < 1000:
                logger.info(
                    "Recovery verification: resolved after %.1fs (score=%.2f, lat=%.1f)",
                    sum(poll_backoff[:attempt]), post_anomaly, post_latency,
                )
                break

            logger.info(
                "Recovery verification: not yet resolved (score=%.2f, lat=%.1f) — retrying...",
                post_anomaly, post_latency,
            )
        except Exception as e:
            logger.warning("Recovery verification poll attempt %d failed: %s", attempt, e)
            if attempt < len(poll_backoff):
                continue
            # Last attempt failed — report will show the error below
            post_anomaly = anomaly_score_before  # assume not recovered
            post_latency = 9999

    # Report generation (after polling, not inside the loop)
    latency_improved = post_latency < 1000
    report_sections.append(f"## Recovery Verification")
    report_sections.append(f"")
    report_sections.append(f"| Metric | Before | After | Status |")
    report_sections.append(f"|--------|--------|-------|--------|")
    report_sections.append(
        f"| Anomaly Score | {anomaly_score_before:.2f} | {post_anomaly:.2f} | "
        f"{'✅ Resolved' if recovered else '⚠️ Still Elevated'} |"
    )
    report_sections.append(
        f"| Latency (ms) | — | {post_latency:.2f} | "
        f"{'✅ Normal' if latency_improved else '⚠️ Elevated'} |"
    )
    report_sections.append(f"")

    if recovered and latency_improved:
        report_sections.append(f"### ✅ Verdict: Anomaly Resolved")
    elif recovered:
        report_sections.append(f"### ⚠️ Verdict: Partially Resolved")
    else:
        report_sections.append(f"### ❌ Verdict: Not Resolved")

    report_sections.append(f"")
    report_sections.append(f"---")
    report_sections.append(f"*Report auto-generated by AetherOps Remediation Executor*")

    return "\n".join(report_sections)


# ── Supervisor ──

def supervisor(state: DiagnosisState) -> Dict:
    """Supervisor agent: follow the plan and handle critic feedback loops.

    Routing priority:
      1. If plan is empty/missing → planner (first run)
      2. If critic rejected and loops remain → llm_diagnostician (re-diagnose)
      3. Follow plan step by step
      4. Plan exhausted → finish (END)
    """
    plan: list = state.get("plan") or []
    step_idx: int = state.get("plan_step_index", 0)
    next_agent: str
    instruction: Optional[str] = None

    # Case 1: No plan yet → run planner
    if not plan:
        next_agent = "planner"
        instruction = "no plan yet"

    # Case 2: Critic rejected diagnosis → loop back to llm_diagnostician
    elif (
        state.get("critic_approves") is False
        and state.get("critic_loop_count", 0) < MAX_CRITIC_LOOPS
    ):
        next_agent = "llm_diagnostician"
        instruction = (
            f"critic rejected diagnosis (loop {state.get('critic_loop_count', 0)}/{MAX_CRITIC_LOOPS})"
        )

    # Case 3: Follow plan
    elif step_idx < len(plan):
        next_agent = plan[step_idx]
        instruction = f"plan step {step_idx + 1}/{len(plan)}: {next_agent}"

    # Case 4: Plan done
    else:
        next_agent = "finish"
        instruction = "all steps complete"

    logger.info("Supervisor → %s (%s)", next_agent, instruction)

    # Increment plan index only when moving forward (not on critic re-diagnose loop)
    new_index = step_idx
    if next_agent in ("planner", "topology_analyst", "causal_analyst",
                       "llm_diagnostician", "critic", "risk_assessor",
                       "remediation_executor"):
        # Only increment if we're moving to a non-loop step
        if not (
            next_agent == "llm_diagnostician"
            and state.get("critic_approves") is False
        ):
            if next_agent != "planner":  # planner sets its own index
                new_index = step_idx + 1
            else:
                new_index = 0  # reset when re-planning

    return {
        "next_agent": next_agent,
        "supervisor_instruction": instruction,
        "plan_step_index": new_index,
    }


# ── Workflow Engine ──

class Workflow:
    """Minimal workflow engine — replaces LangGraph StateGraph.

    Holds a mapping of agent name → callable and an entry point.
    Each agent receives the current state dict and returns a dict of updates.
    The loop reads ``state["next_agent"]`` (set by the supervisor) to decide
    which agent to run next, stopping when ``next_agent == "finish"`` or the
    state sets ``completed=True``.
    """

    def __init__(
        self,
        agents: dict[str, callable],
        entry_point: str,
    ):
        self._agents = dict(agents)
        self._entry = entry_point

    def invoke(self, state: dict) -> dict:
        """Run the workflow loop, mutating *state* in place.

        Each agent returns state updates.  After every non-supervisor agent
        the loop routes back to the supervisor for the next routing decision.
        """
        state = dict(state)
        agent = state.get("next_agent", self._entry)
        while agent in self._agents:
            result = self._agents[agent](state)
            state.update(result)
            # Always route back to supervisor unless workflow is done
            if not state.get("completed") and agent not in ("supervisor", "finish"):
                agent = "supervisor"
            else:
                agent = state.get("next_agent", "finish")
        return state


# ── Graph Builder ──

def build_workflow() -> Workflow:
    """Build and return the multi-agent workflow engine."""
    agents = {
        "supervisor": supervisor,
        "planner": planner,
        "topology_analyst": topology_analyst,
        "causal_analyst": causal_analyst,
        "llm_diagnostician": llm_diagnostician,
        "critic": critic,
        "risk_assessor": risk_assessor,
        "remediation_executor": remediation_executor,
    }
    return Workflow(agents=agents, entry_point="supervisor")


def run_workflow(workflow: Workflow, initial_state: dict) -> dict:
    """Invoke a workflow with START/END/ERROR hooks."""
    trigger_hook(HookEvent.WORKFLOW_START, state=initial_state)
    try:
        result = workflow.invoke(initial_state)
        trigger_hook(HookEvent.WORKFLOW_END, result=result)
        return result
    except Exception as e:
        trigger_hook(HookEvent.WORKFLOW_ERROR, error=str(e))
        raise


