// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadHttp_probe returns the embedded CollectionSpec for http_probe.
func loadHttp_probe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Http_probeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load http_probe: %w", err)
	}

	return spec, err
}

// loadHttp_probeObjects loads http_probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*http_probeObjects
//	*http_probePrograms
//	*http_probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHttp_probeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHttp_probe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// http_probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_probeSpecs struct {
	http_probeProgramSpecs
	http_probeMapSpecs
	http_probeVariableSpecs
}

// http_probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_probeProgramSpecs struct {
	UprobeGrpcInvoke      *ebpf.ProgramSpec `ebpf:"uprobe_grpc_invoke"`
	UprobeHttpReadRequest *ebpf.ProgramSpec `ebpf:"uprobe_http_read_request"`
	UprobeHttpWriteHeader *ebpf.ProgramSpec `ebpf:"uprobe_http_write_header"`
}

// http_probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_probeMapSpecs struct {
	HttpEvents *ebpf.MapSpec `ebpf:"http_events"`
	HttpStart  *ebpf.MapSpec `ebpf:"http_start"`
}

// http_probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_probeVariableSpecs struct {
}

// http_probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHttp_probeObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_probeObjects struct {
	http_probePrograms
	http_probeMaps
	http_probeVariables
}

func (o *http_probeObjects) Close() error {
	return _Http_probeClose(
		&o.http_probePrograms,
		&o.http_probeMaps,
	)
}

// http_probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHttp_probeObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_probeMaps struct {
	HttpEvents *ebpf.Map `ebpf:"http_events"`
	HttpStart  *ebpf.Map `ebpf:"http_start"`
}

func (m *http_probeMaps) Close() error {
	return _Http_probeClose(
		m.HttpEvents,
		m.HttpStart,
	)
}

// http_probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHttp_probeObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_probeVariables struct {
}

// http_probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHttp_probeObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_probePrograms struct {
	UprobeGrpcInvoke      *ebpf.Program `ebpf:"uprobe_grpc_invoke"`
	UprobeHttpReadRequest *ebpf.Program `ebpf:"uprobe_http_read_request"`
	UprobeHttpWriteHeader *ebpf.Program `ebpf:"uprobe_http_write_header"`
}

func (p *http_probePrograms) Close() error {
	return _Http_probeClose(
		p.UprobeGrpcInvoke,
		p.UprobeHttpReadRequest,
		p.UprobeHttpWriteHeader,
	)
}

func _Http_probeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed http_probe_bpfeb.o
var _Http_probeBytes []byte
