// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadProto_classifier returns the embedded CollectionSpec for proto_classifier.
func loadProto_classifier() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Proto_classifierBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load proto_classifier: %w", err)
	}

	return spec, err
}

// loadProto_classifierObjects loads proto_classifier and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*proto_classifierObjects
//	*proto_classifierPrograms
//	*proto_classifierMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProto_classifierObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProto_classifier()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// proto_classifierSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proto_classifierSpecs struct {
	proto_classifierProgramSpecs
	proto_classifierMapSpecs
	proto_classifierVariableSpecs
}

// proto_classifierProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proto_classifierProgramSpecs struct {
	KprobeProtoClassify *ebpf.ProgramSpec `ebpf:"kprobe_proto_classify"`
}

// proto_classifierMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proto_classifierMapSpecs struct {
	ProtoEvents *ebpf.MapSpec `ebpf:"proto_events"`
}

// proto_classifierVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proto_classifierVariableSpecs struct {
}

// proto_classifierObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProto_classifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type proto_classifierObjects struct {
	proto_classifierPrograms
	proto_classifierMaps
	proto_classifierVariables
}

func (o *proto_classifierObjects) Close() error {
	return _Proto_classifierClose(
		&o.proto_classifierPrograms,
		&o.proto_classifierMaps,
	)
}

// proto_classifierMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProto_classifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type proto_classifierMaps struct {
	ProtoEvents *ebpf.Map `ebpf:"proto_events"`
}

func (m *proto_classifierMaps) Close() error {
	return _Proto_classifierClose(
		m.ProtoEvents,
	)
}

// proto_classifierVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProto_classifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type proto_classifierVariables struct {
}

// proto_classifierPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProto_classifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type proto_classifierPrograms struct {
	KprobeProtoClassify *ebpf.Program `ebpf:"kprobe_proto_classify"`
}

func (p *proto_classifierPrograms) Close() error {
	return _Proto_classifierClose(
		p.KprobeProtoClassify,
	)
}

func _Proto_classifierClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed proto_classifier_bpfel.o
var _Proto_classifierBytes []byte
