// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadRedis_trace returns the embedded CollectionSpec for redis_trace.
func loadRedis_trace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Redis_traceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load redis_trace: %w", err)
	}

	return spec, err
}

// loadRedis_traceObjects loads redis_trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*redis_traceObjects
//	*redis_tracePrograms
//	*redis_traceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRedis_traceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRedis_trace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// redis_traceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type redis_traceSpecs struct {
	redis_traceProgramSpecs
	redis_traceMapSpecs
	redis_traceVariableSpecs
}

// redis_traceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type redis_traceProgramSpecs struct {
	KprobeRedisSendmsg *ebpf.ProgramSpec `ebpf:"kprobe_redis_sendmsg"`
}

// redis_traceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type redis_traceMapSpecs struct {
	RedisEvents *ebpf.MapSpec `ebpf:"redis_events"`
	RedisPorts  *ebpf.MapSpec `ebpf:"redis_ports"`
}

// redis_traceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type redis_traceVariableSpecs struct {
}

// redis_traceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRedis_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type redis_traceObjects struct {
	redis_tracePrograms
	redis_traceMaps
	redis_traceVariables
}

func (o *redis_traceObjects) Close() error {
	return _Redis_traceClose(
		&o.redis_tracePrograms,
		&o.redis_traceMaps,
	)
}

// redis_traceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRedis_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type redis_traceMaps struct {
	RedisEvents *ebpf.Map `ebpf:"redis_events"`
	RedisPorts  *ebpf.Map `ebpf:"redis_ports"`
}

func (m *redis_traceMaps) Close() error {
	return _Redis_traceClose(
		m.RedisEvents,
		m.RedisPorts,
	)
}

// redis_traceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRedis_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type redis_traceVariables struct {
}

// redis_tracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRedis_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type redis_tracePrograms struct {
	KprobeRedisSendmsg *ebpf.Program `ebpf:"kprobe_redis_sendmsg"`
}

func (p *redis_tracePrograms) Close() error {
	return _Redis_traceClose(
		p.KprobeRedisSendmsg,
	)
}

func _Redis_traceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed redis_trace_bpfel.o
var _Redis_traceBytes []byte
