// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTc_drop returns the embedded CollectionSpec for tc_drop.
func loadTc_drop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tc_dropBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tc_drop: %w", err)
	}

	return spec, err
}

// loadTc_dropObjects loads tc_drop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tc_dropObjects
//	*tc_dropPrograms
//	*tc_dropMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTc_dropObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTc_drop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tc_dropSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_dropSpecs struct {
	tc_dropProgramSpecs
	tc_dropMapSpecs
	tc_dropVariableSpecs
}

// tc_dropProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_dropProgramSpecs struct {
	TcDropIngress *ebpf.ProgramSpec `ebpf:"tc_drop_ingress"`
}

// tc_dropMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_dropMapSpecs struct {
	TcDropIps *ebpf.MapSpec `ebpf:"tc_drop_ips"`
}

// tc_dropVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_dropVariableSpecs struct {
}

// tc_dropObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTc_dropObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_dropObjects struct {
	tc_dropPrograms
	tc_dropMaps
	tc_dropVariables
}

func (o *tc_dropObjects) Close() error {
	return _Tc_dropClose(
		&o.tc_dropPrograms,
		&o.tc_dropMaps,
	)
}

// tc_dropMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTc_dropObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_dropMaps struct {
	TcDropIps *ebpf.Map `ebpf:"tc_drop_ips"`
}

func (m *tc_dropMaps) Close() error {
	return _Tc_dropClose(
		m.TcDropIps,
	)
}

// tc_dropVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTc_dropObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_dropVariables struct {
}

// tc_dropPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTc_dropObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_dropPrograms struct {
	TcDropIngress *ebpf.Program `ebpf:"tc_drop_ingress"`
}

func (p *tc_dropPrograms) Close() error {
	return _Tc_dropClose(
		p.TcDropIngress,
	)
}

func _Tc_dropClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_drop_bpfel.o
var _Tc_dropBytes []byte
