// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type tcp_rttRttTrackInfo struct {
	SendTsNs uint64
	Saddr    uint32
	Daddr    uint32
	Sport    uint16
	Dport    uint16
	Family   uint16
	_        [2]byte
	Pid      uint32
	_        [4]byte
}

// loadTcp_rtt returns the embedded CollectionSpec for tcp_rtt.
func loadTcp_rtt() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tcp_rttBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcp_rtt: %w", err)
	}

	return spec, err
}

// loadTcp_rttObjects loads tcp_rtt and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcp_rttObjects
//	*tcp_rttPrograms
//	*tcp_rttMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcp_rttObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcp_rtt()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcp_rttSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_rttSpecs struct {
	tcp_rttProgramSpecs
	tcp_rttMapSpecs
	tcp_rttVariableSpecs
}

// tcp_rttProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_rttProgramSpecs struct {
	KprobeTcpSendmsgRtt    *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg_rtt"`
	KretprobeTcpRecvmsgRtt *ebpf.ProgramSpec `ebpf:"kretprobe_tcp_recvmsg_rtt"`
}

// tcp_rttMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_rttMapSpecs struct {
	RttEvents    *ebpf.MapSpec `ebpf:"rtt_events"`
	RttRateLimit *ebpf.MapSpec `ebpf:"rtt_rate_limit"`
	RttTrack     *ebpf.MapSpec `ebpf:"rtt_track"`
}

// tcp_rttVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_rttVariableSpecs struct {
	RttSamplingIntervalNs *ebpf.VariableSpec `ebpf:"rtt_sampling_interval_ns"`
}

// tcp_rttObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcp_rttObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_rttObjects struct {
	tcp_rttPrograms
	tcp_rttMaps
	tcp_rttVariables
}

func (o *tcp_rttObjects) Close() error {
	return _Tcp_rttClose(
		&o.tcp_rttPrograms,
		&o.tcp_rttMaps,
	)
}

// tcp_rttMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcp_rttObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_rttMaps struct {
	RttEvents    *ebpf.Map `ebpf:"rtt_events"`
	RttRateLimit *ebpf.Map `ebpf:"rtt_rate_limit"`
	RttTrack     *ebpf.Map `ebpf:"rtt_track"`
}

func (m *tcp_rttMaps) Close() error {
	return _Tcp_rttClose(
		m.RttEvents,
		m.RttRateLimit,
		m.RttTrack,
	)
}

// tcp_rttVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcp_rttObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_rttVariables struct {
	RttSamplingIntervalNs *ebpf.Variable `ebpf:"rtt_sampling_interval_ns"`
}

// tcp_rttPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcp_rttObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_rttPrograms struct {
	KprobeTcpSendmsgRtt    *ebpf.Program `ebpf:"kprobe_tcp_sendmsg_rtt"`
	KretprobeTcpRecvmsgRtt *ebpf.Program `ebpf:"kretprobe_tcp_recvmsg_rtt"`
}

func (p *tcp_rttPrograms) Close() error {
	return _Tcp_rttClose(
		p.KprobeTcpSendmsgRtt,
		p.KretprobeTcpRecvmsgRtt,
	)
}

func _Tcp_rttClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcp_rtt_bpfeb.o
var _Tcp_rttBytes []byte
