// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type tcp_conntrackConnInfo struct {
	StartNs uint64
	Saddr   uint32
	Daddr   uint32
	Sport   uint16
	Dport   uint16
	Family  uint16
	_       [2]byte
	Pid     uint32
	Role    uint8
	_       [3]byte
}

// loadTcp_conntrack returns the embedded CollectionSpec for tcp_conntrack.
func loadTcp_conntrack() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tcp_conntrackBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcp_conntrack: %w", err)
	}

	return spec, err
}

// loadTcp_conntrackObjects loads tcp_conntrack and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcp_conntrackObjects
//	*tcp_conntrackPrograms
//	*tcp_conntrackMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcp_conntrackObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcp_conntrack()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcp_conntrackSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_conntrackSpecs struct {
	tcp_conntrackProgramSpecs
	tcp_conntrackMapSpecs
	tcp_conntrackVariableSpecs
}

// tcp_conntrackProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_conntrackProgramSpecs struct {
	KprobeTcpClose   *ebpf.ProgramSpec `ebpf:"kprobe_tcp_close"`
	KprobeTcpConnect *ebpf.ProgramSpec `ebpf:"kprobe_tcp_connect"`
}

// tcp_conntrackMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_conntrackMapSpecs struct {
	ConnEvents    *ebpf.MapSpec `ebpf:"conn_events"`
	ConnRateLimit *ebpf.MapSpec `ebpf:"conn_rate_limit"`
	ConnTrack     *ebpf.MapSpec `ebpf:"conn_track"`
}

// tcp_conntrackVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_conntrackVariableSpecs struct {
	ConnSamplingIntervalNs *ebpf.VariableSpec `ebpf:"conn_sampling_interval_ns"`
}

// tcp_conntrackObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcp_conntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_conntrackObjects struct {
	tcp_conntrackPrograms
	tcp_conntrackMaps
	tcp_conntrackVariables
}

func (o *tcp_conntrackObjects) Close() error {
	return _Tcp_conntrackClose(
		&o.tcp_conntrackPrograms,
		&o.tcp_conntrackMaps,
	)
}

// tcp_conntrackMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcp_conntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_conntrackMaps struct {
	ConnEvents    *ebpf.Map `ebpf:"conn_events"`
	ConnRateLimit *ebpf.Map `ebpf:"conn_rate_limit"`
	ConnTrack     *ebpf.Map `ebpf:"conn_track"`
}

func (m *tcp_conntrackMaps) Close() error {
	return _Tcp_conntrackClose(
		m.ConnEvents,
		m.ConnRateLimit,
		m.ConnTrack,
	)
}

// tcp_conntrackVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcp_conntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_conntrackVariables struct {
	ConnSamplingIntervalNs *ebpf.Variable `ebpf:"conn_sampling_interval_ns"`
}

// tcp_conntrackPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcp_conntrackObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_conntrackPrograms struct {
	KprobeTcpClose   *ebpf.Program `ebpf:"kprobe_tcp_close"`
	KprobeTcpConnect *ebpf.Program `ebpf:"kprobe_tcp_connect"`
}

func (p *tcp_conntrackPrograms) Close() error {
	return _Tcp_conntrackClose(
		p.KprobeTcpClose,
		p.KprobeTcpConnect,
	)
}

func _Tcp_conntrackClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcp_conntrack_bpfeb.o
var _Tcp_conntrackBytes []byte
