// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTrace_context returns the embedded CollectionSpec for trace_context.
func loadTrace_context() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Trace_contextBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load trace_context: %w", err)
	}

	return spec, err
}

// loadTrace_contextObjects loads trace_context and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*trace_contextObjects
//	*trace_contextPrograms
//	*trace_contextMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTrace_contextObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrace_context()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// trace_contextSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trace_contextSpecs struct {
	trace_contextProgramSpecs
	trace_contextMapSpecs
	trace_contextVariableSpecs
}

// trace_contextProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trace_contextProgramSpecs struct {
	KprobeTraceContext *ebpf.ProgramSpec `ebpf:"kprobe_trace_context"`
}

// trace_contextMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trace_contextMapSpecs struct {
	TraceContextEvents *ebpf.MapSpec `ebpf:"trace_context_events"`
}

// trace_contextVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trace_contextVariableSpecs struct {
}

// trace_contextObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTrace_contextObjects or ebpf.CollectionSpec.LoadAndAssign.
type trace_contextObjects struct {
	trace_contextPrograms
	trace_contextMaps
	trace_contextVariables
}

func (o *trace_contextObjects) Close() error {
	return _Trace_contextClose(
		&o.trace_contextPrograms,
		&o.trace_contextMaps,
	)
}

// trace_contextMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTrace_contextObjects or ebpf.CollectionSpec.LoadAndAssign.
type trace_contextMaps struct {
	TraceContextEvents *ebpf.Map `ebpf:"trace_context_events"`
}

func (m *trace_contextMaps) Close() error {
	return _Trace_contextClose(
		m.TraceContextEvents,
	)
}

// trace_contextVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTrace_contextObjects or ebpf.CollectionSpec.LoadAndAssign.
type trace_contextVariables struct {
}

// trace_contextPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTrace_contextObjects or ebpf.CollectionSpec.LoadAndAssign.
type trace_contextPrograms struct {
	KprobeTraceContext *ebpf.Program `ebpf:"kprobe_trace_context"`
}

func (p *trace_contextPrograms) Close() error {
	return _Trace_contextClose(
		p.KprobeTraceContext,
	)
}

func _Trace_contextClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trace_context_bpfel.o
var _Trace_contextBytes []byte
